openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: {SomeGeneratedURL}/short
    description: Send Links to this URL to Return Shortened URL and Original URL as JSON (Returns Both to Give Batch Feedback)
  - url: {SomeGeneratedURL}/expand
    description: Send Short URL to this URL to Return Original URL as JSON
paths:
  /short:
    POST:
      summary: Returns a JSON Object with originalURL and shortURL.
      description: Creates Short URL.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  orignialURL: string
    /expand:
    POST:
      summary: Returns a JSON Object with originalURL and shortURL.
      description: Retrieves originalURL.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  shortURL: string