openapi: 3.0.0
info:
  title: URL Shortener API
  description: 
  version: 0.1.9
servers:
  - url: /{shortURL}
    description: Send Links to this URL to Return Shortened URL and Original URL as JSON (Returns Both to Give Batch Feedback)
  - url: /expand
    description: Send Short URL to this URL to Return Original URL as JSON
paths:
  /short:
    POST:
      summary: Returns a JSON Object with originalURL and shortURL.
      description: Creates Short URL.
      responses:
        '200':    # status code
          description: Successfully Added to DyanmoDB
          content:
            application/json:
              schema: 
                type: array
                items: 
                  originalURL: string
    /{shortURL}:
    GET:
      summary: Redirrects user to the original URL
      description: Retrieves original URL from DynamoDB and redirrects to it
      responses:
        '308':    # status code
          description: Successfully Retrieved from DynamoDB 
          content:
            application/json:
              schema: 
                type: array
                items: 
                  shortURL: string