AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  URLShortFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: short.handler
      Runtime: nodejs8.10
      Events:
        URLShortApi:
          Type: Api
          Properties:
            Path: /short
            Method: GET
  URLExpandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: expand.handler
      Runtime: nodejs8.10
      Events:
        URLExpandApi:
          Type: Api
          Properties:
            Path: /expand
            Method: GET
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: Number
        - AttributeName: url
          AttributeType: String
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: url
          KeyType: RANGE
      