AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  URLShortFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: short.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Events:
        URLShortApi:
          Type: Api
          Properties:
            Path: /short
            Method: POST
  URLExpandFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: expand.handler
      Runtime: nodejs8.10
      Policies: AmazonDynamoDBFullAccess
      Events:
        URLExpandApi:
          Type: Api
          Properties:
            Path: /expand
            Method: POST
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: shortuuid
          AttributeType: S
        - AttributeName: longurl
          AttributeType: S
      KeySchema:
        - AttributeName: shortuuid
          KeyType: HASH
        - AttributeName: longurl
          KeyType: RANGE
      ProvisionedThroughput:      
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: "shortURL"